### ISSUE TITLE
Holes inside $ glyph

### ISSUE THREAD

**Issue by Altren** [Chlumsky/msdfgen#106]
I'm rendering '$' from DejaVuSans.ttf. The glyph look relatively simple: no sharp edges or complex self intersections, but with a relatively big source image it have many holes. Attaching render, based on 32x32, all other glyphs are ok with 24x24.
![_dollar](https://user-images.githubusercontent.com/1607435/82743257-849d7b80-9d71-11ea-844f-9416cb868acd.png)
![render_dollar](https://user-images.githubusercontent.com/1607435/82743259-86673f00-9d71-11ea-9c1f-422c05c46e12.png)
Here's script I used for generation: `msdfgen.exe -font DejaVuSans.ttf '$' -size 32 32 -pxrange 4 -autoframe -testrender render_dollar.png 512 512 -o _dollar.png`

**Comment by Chlumsky** [comment]
Unfortunately, this is due to a combination of two things - 1. the vertical bar is thinner than other features in the font, and 2. the current error correction is not perfect and lets some artifacts like these slip through.

The first point means that it is at least tricky to properly conserve sharp corners for the vertical bar, and may be in fact impossible if it were any thinner (in proportion to the resolution of the distance field). However, in this case, choosing a different edge coloring does help, for example adding `-seed 4145` to the command you posted improves the result significantly, although it's still not perfect. However, the edge coloring algorithm isn't advanced enough to be able to come up with it by itself. This is something I'd like to work on in the future.

As for the second point, even if the line is this thin, it should still be possible to draw it without artifacts at the cost of not preserving all of the corners. I have been working on a new version of the error correction algorithm that uses a completely new approach to detect these artifacts and should be able to reliably find all of them. Its main downside is its performance cost and potential false positives, so I'm still working on it. For you, I have published a WIP version of this into the [interpolation-error-correction](https://github.com/Chlumsky/msdfgen/tree/interpolation-error-correction) branch, so you can test if it works for you better than the mainline version. If you only use the compiled version, you can download this: [msdfgen-experimental-interpolation-error-correction.zip](https://github.com/Chlumsky/msdfgen/files/4673266/msdfgen-experimental-interpolation-error-correction.zip)

**Comment by Altren** [comment]
Thank you for the WIP version. With the current settings result became better, but the cost was the sharp corners. I believe that holes always looks like a bug, so not sharp corners is a worthy trade-off to avoid that.
![render_dollar_32_new](https://user-images.githubusercontent.com/1607435/82757073-cae0f200-9de6-11ea-958c-17d6b066162a.png)
And a few more tests you might be interested to see:
24x24 image with old and new versions:
![render_dollar_24_old](https://user-images.githubusercontent.com/1607435/82757121-08457f80-9de7-11ea-81ef-6c68e7b0b487.png)
![render_dollar_24_new](https://user-images.githubusercontent.com/1607435/82757123-0aa7d980-9de7-11ea-8c56-c77b9b78d29c.png)

**Comment by Chlumsky** [comment]
You need to realize that for the 24x24 one, the thickness of the vertical bar is about the same as the distance between pixels of the distance field. At that point, it's pretty much impossible to draw it well. For example, with `sdf` and `-scale 0.6 -translate 8.3 8.3`, the bar disappears comletely, as it is located entirely in between two pixel columns of the SDF.

**Comment by Altren** [comment]
Contrary, many characters can be rendered in much smaller resolution, so with a reliable metric I can create perfectly optimal atlas, where each glyph takes as much space as really necessary.

**Comment by Chlumsky** [comment]
The new error correction algorithm which fixes this issue has been integrated into the mainline in 010f3c92f10a2cf7b4e64b98fe1a2e959fe3667c and released in version 1.8.
