### ISSUE TITLE
Texture atlas

### ISSUE THREAD

**Issue by boulabiar** [Chlumsky/msdfgen#11]
msdfgen allows the creation of a single texture per character or vector each time.
What about creating a texture map of all chars in a font?

In terms of packing, should every char be in a full square area or is it possible to have more packed elements ?

**Comment by mikemorris** [comment]
Binpacking into a single texture feels like something that should be an implementation detail at a higher level, not integrated into this project directly.

**Comment by Chlumsky** [comment]
It is up to you what you do with the generated images. Nobody says that it is the final texture you have to use. That's the main reason I also made it available as a library - so that you can programatically use it to generate multiple images and stitch them together before saving to a file. And yes, you can do this just like with ordinary distance fields, the only thing to be careful about are outside colors (red, green, blue) which often fill the surroundings of the glyph - don't let different colors touch directly when placing the images next to each other, for example add a 1 pixel black padding to be sure.
