### ISSUE TITLE
Overlapping glyph contours produce positive values

### ISSUE THREAD

**Issue by dendy** [Chlumsky/msdfgen#110]
Here is an example of the font which has such curves:
https://github.com/MostofaRiad/PicEdit-Android/raw/master/app/src/main/assets/fonts/Eunjin.ttf

msdfgen msdf -font Eunjin.ttf \'e\' -autoframe -format png -o e.png -size 128 128

The overlapping part supposed to be inside glyph, but instead it produces positive distances. I guess once closest curve is found it is used to calculate the distance. Cannot figure out what options should be used to fix this.

![e](https://user-images.githubusercontent.com/103317/89038144-a167a980-d2f4-11ea-9088-c35490c3aa68.png)

**Comment by Chlumsky** [comment]
Yeah, unfortunately self-intersecting contours are not supported by this program and are considered bad input. The correct approach is to apply some kind of vector preprocessing to convert the glyph to the appropriate format (i.e. one contour for the outer part and another for the hole).

That being said, I don't see any areas where distance has the wrong sign in the supplied SDF image. That's because it's patched by the scanline pass, but the distance values themselves are wrong and it may result in some artifacts in the problematic area.

**Comment by Chlumsky** [comment]
Preprocessing of shape geometry has been implemented in the project via the Skia library in 9d22335ea093422d7bf212d31bfaa6adcb9b89f0 and released in version 1.8, so this issue is now fixed.
