### ISSUE TITLE
Default PxRange is 2, it cause a problem when I try to do outline effect.

### ISSUE THREAD

**Issue by Chinayang1** [Chlumsky/msdfgen#139]
Default PxRange:
![outline_px2](https://user-images.githubusercontent.com/20715080/149136946-e66dafcc-539f-474a-96dc-ee7a4a68baca.png)

PxRange 16:
![outline_px8](https://user-images.githubusercontent.com/20715080/149136958-fa556299-b083-4296-a4b5-fcbbbd407974.png)

It's spent my a lot of time to realize this. The distance value on GPU fastly smooth from 0 to 1.0f. Compare distance is invalid to find outline.

![pxRange_16_thinness](https://user-images.githubusercontent.com/20715080/149136904-61c2fca9-f660-41cf-a41f-8ef23de69c2b.png)
And  even on high pxRange, Thinness effect doesn't work for art font with different thinness of a letter.

**Comment by Chlumsky** [comment]
The default value of pxRange is not intended for drawing outlines but it is sufficient for basic rendering - that's why you can change it. As for the last "problem" with "different thinness" that's not something that can be solved with this (or any similar) software and was never claimed to be. All it provides is signed distance from the _edge_, not from the center.
