### ISSUE TITLE
Update/retarget project to VS2019

### ISSUE THREAD

**Issue by benui-dev** [Chlumsky/msdfgen#146]
The existing .sln file in the project is requires v140 / Visual Studio 2015.

As far as I know 2019 is much more common these days. Would it be possible to update the .sln to v142 / 2019?

**Comment by Type1J** [comment]
That's probably true, but if you use Visual Studio 2019's Open Folder feature, it will read the CMakeLists.txt file instead of the .sln file. I think that the .sln is there just to support older version of Visual Studio without direct support for CMake built-in. I could be wrong, though.

**Comment by Chlumsky** [comment]
You can use CMake, you can just open the solution in a newer version, or you can upgrade it in your local copy / fork. If I changed it to VS2019, it wouldn't help much because some would say it should actually be VS2022 because that's the current version, and others might say that they can no longer open it because they have VS2017. I am planning to remove the solution file and only use CMake in the future.
