### ISSUE TITLE
Chinese character rendering issues

### ISSUE THREAD

**Issue by RikiLee** [Chlumsky/msdfgen#181]
I use msdfgen.exe to generate an MSDF texture of the Chinese character '中' in size 32 * 32, but when I render it to an image with size 1024 * 1024,  some strokes are broken.  

When I change the texture size to 64 * 64, the result is better, but there still are a few holes in the character.

Is this a bug or did I misuse something? 

The font file which I use is simsun.ttc , and the Unicode of the character is 0x4e2d. And many other Chinese characters have this problem too.

**Comment by Chlumsky** [comment]
Post pictures.

**Comment by RikiLee** [comment]
![render](https://github.com/Chlumsky/msdfgen/assets/21985815/5c2d5193-7dd8-4efc-a5b6-5738cb517a8e)
This image is rendered by a 32 * 32 size texture. 
![render](https://github.com/Chlumsky/msdfgen/assets/21985815/19297c22-47eb-4f89-94a5-071b91e49fed)
This image is rendered by a 64 * 64 size texture.  The hole is very small.

**Comment by Chlumsky** [comment]
The lines in the font are way too thin for low resolution distance fields. Every line should be at least 1 or 2 pixels thick in the distance field in order to be encoded properly.

**Comment by RikiLee** [comment]
When I use a 128 *128 size texture, this problem disappeared. Thank you. 
By the way, is there any way to solve this problem when using a low-resolution SDF texture?

**Comment by Chlumsky** [comment]
You would have to make sure that the opposite edges that are close together have different colors in the MSDF scheme, but since there are only 3 available colors and you also need to switch them at corners, it may not be possible to satisfy both constraints. It is likely possible to generalize MSDF to 5 or more colors (channels), which would require multiple texture lookups, but I haven't tried implementing this.
