### ISSUE TITLE
Straight edges instead of curved.

### ISSUE THREAD

**Issue by paulhoux** [Chlumsky/msdfgen#23]
Hi Chlumsky,

I created a (roughly) 64x64 glyph texture using the Showcard Gothic font and noticed that, when rendering at large sizes, the inner curve of the R is made from straight edges, instead of a nice curve. The same is not true for the outer curves of the R. Other glyphs show similar problems. 

![2016-07-23_205101](https://cloud.githubusercontent.com/assets/304908/17079678/0d380f0a-5118-11e6-8053-4992413d5d35.png)

When examining the font file, it's clear that the font is using a smooth curve. I tried increasing `MSDFGEN_CUBIC_SEARCH_STEPS` to 40, but that did not do anything. 

Do you have any idea what might cause this?

**Comment by underscorediscovery** [comment]
![output](https://cloud.githubusercontent.com/assets/236374/17079715/2a205688-50f3-11e6-9e5b-d208736da442.png)

![render](https://cloud.githubusercontent.com/assets/236374/17079716/2be989ee-50f3-11e6-80ee-2367c8819012.png)

I think I saw similar here (Droid Sans Bold), even though the glyph size is 20x20 the output at 1024 is great, but there is noticeable stepping on inner paths.

**Comment by Chlumsky** [comment]
The signed distance field representation is not lossless and this is an effect of that. The reason you're perceiving it on the inner curve only is that it is much more curved, but the outer curve is actually also made up of lines of the same length, but it's less noticeable because they are connected at less sharp angles.

The length of the lines is actually proportional to the distance between pixels of the distance field, and they arise from the **line**ar interpolation. One way to prevent this would be to use bicubic interpolation, but I strongly advised against that as although it may improve the appearance of some curves (that don't change too unpredictably) at this extreme magnification, it will basically mess up everything else.

My actual solution would be to just increase the distance field resolution if this concerns you too much, but I believe even that is unnecessary unless you're actually targeting this gigantic text size in particular.

**Comment by Chlumsky** [comment]
Here is your G with bicubic interpolation:

![resample](https://cloud.githubusercontent.com/assets/18639794/17080173/da4d31ac-5125-11e6-96bc-33fb16c115f2.png)

The curves are better but you can already see the beginning of an artifact where I marked it. I made a script for this in [Shadron](http://steamcommunity.com/sharedfiles/filedetails/?id=726757501), too bad you can't try it just yet. :)

**Comment by underscorediscovery** [comment]
Yea I agree on that front, I was mostly adding to the notes of effects. It's probably possible to mix interpolation types based on angle and look ahead if you were really that inclined to eliminate the lines. I've been more than happy with the results otherwise. 

I'm also looking forward to Shadron, I saw it pop up on my twitter feed and look forward to trying it out.

**Comment by paulhoux** [comment]
Thanks for your replies. It turned out that I was incorrect in thinking 64x64 texels were used for each glyph on the texture. Instead, only 32x32 texels were used, causing the artifacts mentioned in this issue. By increasing the area to 64x64 texels, curves in the font became much smoother. 

Feel free to close the issue.
