### ISSUE TITLE
Portability of "fwidth()" in GLSL on various platforms

### ISSUE THREAD

**Issue by Andos** [Chlumsky/msdfgen#33]
I have found that the fwidth() GLSL call is only supported on newer computers. Old PC's with intel graphics cards and similar simply fails to load the GLSL shader because of that function usage despite it being available since GLSL since v1.10.
Use of the fwidth() function also doesn't seem to work when compiling OpenGL projects with the ANGLE project (angleproject.org)

Is there a more portable way to get this information?
Was hoping I could avoid resorting to manual derivative calculations by doing several texture lookups.

**Comment by underscorediscovery** [comment]
For ANGLE, it might be because the derivatives are an extension: `GL_OES_standard_derivatives`. You usually call getExtension and add an `: enable` line in the shader for these targets to enable it, which makes fwidth available. [Here's an example of one with a fallback in the shader](https://github.com/stackgl/glsl-aastep) (I haven't tried it).

For older buggy/incomplete drivers I think you might have to do the usual approaches, like detecting the availability if possible, and if still failing (some bad drivers pretend to have things they don't actually have) keep a list of broken ones with an unsupported note, or use the list to do a safe fallback.

**Comment by Chlumsky** [comment]
I don't know about your exact use case, but you only need to use `fwidth` if you draw text with anti-aliasing in a 3D perspective (where scale isn't constant throughout the image). In all other cases, you should supply a constant value instead.
