### ISSUE TITLE
Use a more permissive license

### ISSUE THREAD

**Issue by albert-wang** [Chlumsky/msdfgen#4]
I love the work you've done on this project, and would love to use it for rendering text in my game, but the the nature of the GPL makes me wary to do so. In particular, I want to support dynamic glyph generation, which involves integrating some of the code you've written, but GPL licensing means that this library wouldn't be a good fit for me. 

I think that licensing the code under a less restrictive license, such as [MIT](https://opensource.org/licenses/MIT) or [FreeBSD](https://opensource.org/licenses/BSD-3-Clause) license would allow more people to try out this cool rendering technique. Both the MIT and FreeBSD licenses are GPL compatible and Open Source Initiative approved, so there shouldn't be any loss of freedom.

**Comment by Type1J** [comment]
I agree. How would you feel about switching to MIT or BSD?

**Comment by Chlumsky** [comment]
I don't know. I don't understand this licensing stuff and would prefer not having to deal with it at all. The reason I chose this one is I thought there might be a very small chance that maybe even a large company may find my technology useful for their game engine, and then they may want to buy a proprietary license from me. If you are an "indie" developer though, I have no problem with you using my code in your game and not releasing it under GPL.

Also, I forgot to mention that the code, in its current form, isn't very well suited for dynamic glyph generation because it uses a brute force search for finding the closest edges, computing the distance from each at every pixel. That is something that should probably be improved.

**Comment by elfring** [comment]
>If you are an "indie" developer though, I have no problem with you using my code in your game and not releasing it under GPL.

I suggest to reconsider such a feedback. I would appreciate if you [will support the software freedom better by the chosen licence](https://www.gnu.org/licenses/gpl-faq.html#WhyUseGPL "Why should I use the GNU GPL rather than other free software licenses?").

**Comment by zao** [comment]
That's a very kind gesture, as long as one can motivate it to themselves that it is legally fine.

I personally hope that the future publication is detailed enough to make my own compute-driven implementation.

**Comment by Type1J** [comment]
@Chlumsky Your libarary has a very simple API, which makes it attractive. I can appreciate wanting to provide a comertial license while also releasing under GPL,  but I think that you should put that in your readme.md file for clarity.

As far as indies go: You're statement that you don't mind here wouldn't help me if anybody (not nessisarily you) legally challenged my use of your library in a closed source game. I can't walk that legal tightrope, and most indies can't either.

If you want your library used be the most people, then going with BSD or MIT is really the best way. You will get copyright notices posted in game manuals or credit screens, and contributions from people who wouldn't otherwise contribute. 

GPL will keep the library academic only, unless you post that the comertial license option is available with pricing. Less contributions come that way, though.

I would gladly donate with PayPal, or even go after or fund bounties on issues that you post, if you released under BSD or MIT.

**Comment by kkaefer** [comment]
Throwing my vote in for a less restrictive license like BSD or MIT. We'd like to use this in [Mapbox GL](http://github.com/mapbox/mapbox-gl-native), (see [ticket](https://github.com/mapbox/mapbox-gl-native/issues/137)), but including GPL licensed code isn't an option for us.

**Comment by bkaradzic** [comment]
> and then they may want to buy a proprietary license from me.

In reality this doesn't happen, rather someone just rewrites your GPL code into company proprietary code.

Just mentioning GPL anywhere is conversation non-starter with company business people...

> I have no problem with you using my code in your game and not releasing it under GPL.

License has to state that explicitly.

Anyhow I support change to permissive BSD or MIT, it simplifies adoption as is, and you get credited for it.

p.s. @elfring is obnoxious bot, just ignore him...

**Comment by underscorediscovery** [comment]
I was excited about this till I saw mention of GPL, I hope for a permissive license as well. 

(p.s Google uses Apache v2, similar to MIT but with an explicit patent clause, to protect their users from licensing worries and allow it to be used in wider audiences including big companies and the like)

**Comment by LB--** [comment]
> I don't understand this licensing stuff and would prefer not having to deal with it at all.

Perhaps consider http://www.unlicense.org/ then.
> Because you have more important things to do than enriching lawyers or imposing petty restrictions on users of your code.

**Comment by mattdesl** [comment]
Throwing in my vote. I'd love to use this for art/experiential projects in WebGL, but I tend to stay far away from GPL.

**Comment by tmilker** [comment]
I too would like to see an MIT/Apache/BSD style license.  I would love to use this in an indie game but GPL makes it a non-starter and I'd rather spend time working on a game instead of re-implementing your thesis.  Happy to give credit where credit is due for all libraries used, of course.

**Comment by Chlumsky** [comment]
But if this legal stuff is so strict, am I even allowed to change the license now?

**Comment by zao** [comment]
As long as all authors agree, you can license versions of your work under whatever license you want.
This is why larger projects with many contributors tend to assign rights for contributed code to a single legal entity or sign contribution agreements.

As you're assumedly alone on this project thus far, you can trivially change the license of future versions.

What you cannot do is revoke past versions which are licensed under the GPL, they retain the rights they have been granted.

**Comment by Type1J** [comment]
A CONTRIBUTING.md is used in many project to transfer copyright when pull requests are given.

**Comment by midnite8177** [comment]
The reality is that by choosing GPL you will reduce the list of possible users of your library (GPL requires users to release their source as GPL also). It is ok if that is your intention, it is your code, your decision. Many places (indie to big) will ban the use (and viewing) of any GPL code.

You are forced to choose GPL if a library you use is GPL. TinyXML2 and LodePNG are both zlib license. FreeType is dual licensed (a BSD style and GPL, you pick which one you want).

Use websites such as tldrlegal.com and choosealicense.com to help understand the situation.

If you do want to change the license you need to get the permission from all the authors involved (sounds like just you) and bump the version to 1.1. Version 1.0 is forever GPL.

As others have said, all users right now must use your library as GPL. So small indie to big AAA would have to release the source code to their engine should they use your library. For some that isn't possible, so they can't/won't. You would also have to state that a commercial license is available for purchase should GPL not be suitable (if you want to stay GPL but get a big company to buy it).

**Comment by Chlumsky** [comment]
Alright, I have changed it. Hope you are happy now.
