### ISSUE TITLE
Glyph section inverted & overlap issue

### ISSUE THREAD

**Issue by Spoondog** [Chlumsky/msdfgen#40]
Couple of issues I'm running into while processing some font glyphs - any workarounds appreciated.

First one is, the bottom part of the Q is inverted:
![image](https://cloud.githubusercontent.com/assets/7598230/25362352/775bea92-29a7-11e7-9778-f93c1d6a3e4e.png) 
![image](https://cloud.githubusercontent.com/assets/7598230/25362358/823866de-29a7-11e7-8dba-453c7e536ded.png)

I've tried -keeporder and -reverseorder .. I saw something about a -seed parameter but I can't find any proper info about it so I'm not sure if I can use that to get around this?

The other one is just the overlap on this "D" is a bit funky:

![image](https://cloud.githubusercontent.com/assets/7598230/25362452/0f416620-29a8-11e7-9d3d-b4c170402141.png) 
![image](https://cloud.githubusercontent.com/assets/7598230/25362456/14439300-29a8-11e7-90e6-1eb599c76a45.png)

I'm guessing that one is pretty hard to fix but worth reporting.

Both are using -autoframe

The font I'm using is "Most Wasted": http://www.dafont.com/mostwasted.font

**Comment by Spoondog** [comment]
By the way - is there a way to just do a -testrender of an existing msdf? If not, that'd be really useful if we are trying to manually fix issues like this in PS. I'm going to implement the shader shortly anyway so I can test there, but it'd still be a nice to have.

**Comment by Chlumsky** [comment]
This library is very sensitive to errors / artifacts in the path specification, which this particular font seems to be full of. The issue in the first example (Q) is clearly the bottom piece having reverse winding than everything else, which I'm surprised isn't a problem in other applications, because it seems pretty ambiguous as to how to interpret it. The D is overlapping contours, which should have been recently fixed, but it seems not completely, and the last one seems like a bunch of forgotten points in the middle, which break it.

The solution would be cleaning up the input paths.

The main.cpp doesn't have a testrender only mode, but you can do it quite simply if you write your own and interface with the library.

**Comment by Chlumsky** [comment]
Should be fixed in the latest version by scanline pass.
