### ISSUE TITLE
Closest edge search performance

### ISSUE THREAD

**Issue by Chlumsky** [Chlumsky/msdfgen#5]
Currently, the closest edge segment to a point in the distance field is found with a brute force approach, comparing distances of all edges. For use in runtime glyph map generation, it is necessary to make this process more efficient. If an efficient closest edge lookup is implemented, it will not be a problem to integrate with my method of multi-channel distance field generation.

**Problem definition:**

Implement a data structure that holds a set of edge segments (line segments, quadratic and cubic Bézier curves), some of which may share an endpoint, but generally do not form closed paths, and that supports efficient lookup of the closest edge segment (in terms of absolute euclidean distance) to a given point in the plane.

For the distance, the computation implemented in `EdgeSegment::signedDistance` can be used (the absolute value of the result).

Note that if a common endpoint of two edges is the closest point, it must either produce both, or correctly choose the edge that is considered closer by the same logic used in my SignedDistance class.

Any suggestions on how to implement this are welcome.

**Comment by rougier** [comment]
Do you test directly against all segments and Bézier curves ? Would it be worth testing first Bézier curves against their bounding box and reject them early if a segment is already closest ? Of course, this add supplementary tests but on average, maybe the extra test will make things faster.

**Comment by Jiboo** [comment]
Hello,

This project is really inspiring, great work. I'm still trying to digest this all.

I'm not sure this is not what rougier is already saying, but here's my 2c for this problem: Maybe subdivide the shape in sections (a grid seems simple enough, but maybe some other subdivision would be better adapted)?

You could just add to Shape an array for thus sections (structures holding section bounds and a list of indices to Contours already stored in the Shape), that would hold all Contours which bounding box overlap the section bounds, and instead of iterating the bitmap only by x&y, iterate by sections first, and iterate only on the list of Contours we found earlier.

Although, there might be some edge cases like a line close to the edge of a section, maybe we can search for a bit more percentage than the section bounds to mitigate that. Or a small grid, like 4 or 9 sections.

Bye,
JB.

**Comment by prepare** [comment]
Hello I want to present my idea about it


I have a modified version of your Msdf gen.

I call it _Msdf3_, 

**I optimize 'Closest edge search' by using  'closet edges lookup table bitmap'**

I have implement it here...

---

**1. PixelFarm's LcdEffect SubPixelRendering Atlas texture**

(this is just a based case)

(click on the image to see detail)

![stencil_lcd_effect](https://user-images.githubusercontent.com/7447159/76663728-877f3180-65b4-11ea-9d59-9c902f35882c.gif)

_PixelFarm's LcdEffectSubPixelRendering Atlas Texture, built-time about **220ms**_


---

**2. Msdf gen,C# port from original**

![msdf](https://user-images.githubusercontent.com/7447159/76664011-84387580-65b5-11ea-888a-642546615eaf.gif)

_Msdf, C# version,  built-time about **7,101ms**_



---
**3. a Modified version, (I call it 'Msdf3')**

![msdf3](https://user-images.githubusercontent.com/7447159/76664110-ce215b80-65b5-11ea-8c4b-aa3bfcaa73d3.gif)

_Msdf3, C# version,  built-time about **1,096ms**_




Event the result images are different, but it give the acceptable glyph image,
(see later)

**Comment by prepare** [comment]
Msdf3
---

Our version is an extension to the original technique (Msdf, see https://github.com/Chlumsky/msdfgen). 


It optimizes 'nearest-edge searching' by using 'classic scanline fill' and encode
the pixel-curve data into a lookup bitmap.

Then it go to original Msdf gen phase, 
this time instead of check all pixels, 

it use the lookup bitmap to decode edge data that are responsible for the 
specific bitmap.

With a given pixel,  the choices are

1. no edge for this pixel, => finish here

2.  only 1 edge for this pixel, just calculate distant from a pixel to that edge

3.  more than 1 edge, just calculate the repsonsible edges (mostly just 2-3 edges, on the 
corners, esp overlap edges)

so it go faster


---

for Msdf, see https://github.com/PaintLab/PixelFarm/tree/master/src/PixelFarm/PixelFarm.Drawing/7_CpuBlitPainter/Msdf

and Msdf3, see https://github.com/PaintLab/PixelFarm/tree/master/src/PixelFarm/PixelFarm.Drawing/7_CpuBlitPainter/Msdf3


![msdf_code_in_vs](https://user-images.githubusercontent.com/7447159/76665034-f3fc2f80-65b8-11ea-8a5c-facc2f6f733d.png)
_blue rect is original Msdf, and red rect is Msdf3_

**Comment by prepare** [comment]
Closest Edge Lookup Table
---

Closest edge lookup table bitmap, each pixel contains encoding data of responsible edges
over that pixel. 

This render with 'classic scanline' technqiue.

I use my PixelFarm's Agg (Antigrain geometry, C# port) the render it.

 

![msdf3_glyph_x_lut](https://user-images.githubusercontent.com/7447159/76665489-a385d180-65ba-11ea-9e3d-299517630396.png)

_Roboto font,Closest edge lookup table bitmap_

---

![msdf3_glyph_x](https://user-images.githubusercontent.com/7447159/76665494-a680c200-65ba-11ea-83f7-82ff98584a1a.png)

_Roboto font, Msdf output, 8 times scale up, still sharp :)_

Please note that this version has some artifacts, cause by lut phase, It will be fixed later

**Comment by prepare** [comment]
**Another glyph-B,  Roboto font**
This shows both curve segments and line segment



![msdf3_glyph_b_lut](https://user-images.githubusercontent.com/7447159/76668595-4c80fc00-65bc-11ea-9f4d-3e91d556ca84.png)
_Closest edge lookup table bitmap_

---

![msdf3_glyph_b](https://user-images.githubusercontent.com/7447159/76668683-56a2fa80-65bc-11ea-9a45-358e670086b1.png)

_Roboto font, Msdf output, 8 times scale up, still sharp :)_

Please note that this version has some artifacts, cause by lut phase, It will be fixed later

**Comment by prepare** [comment]
Closest Edge Lookup Table in the form of bitmap
---

This is some detail about the lookup bitmap creation of glyph X, Roboto font

see more detail https://github.com/PaintLab/PixelFarm/issues/55#issuecomment-598998793

![s1_enh1](https://user-images.githubusercontent.com/7447159/76673542-ce7f1e00-65d8-11ea-88d3-72a3206980cd.png)
_1_


---


![s2_enh](https://user-images.githubusercontent.com/7447159/76673645-99270000-65d9-11ea-8eb0-c1b3332fb786.png)
_2_

---

3,4 ... final

![s_final_enh](https://user-images.githubusercontent.com/7447159/76673698-1bafbf80-65da-11ea-838a-988b909483f8.png)
_final_

**Comment by thygrrr** [comment]
I remember this problem from computational geometry, but it's been literally 20 years.

I only know the German terms, but this Wikipedia overview describes a few approaches for line segments with favourable runtimes.

https://en.m.wikipedia.org/wiki/Point_location

Regarding curves, I'm still wondering why a AABB bounding volume hierarchy could not help bring this down to m*log(n). Distance tests to reject subtrees are cheap for each AABB, and proper hierarchy means no single segment is in the same bounding volume (leaf).

I wonder what the frequency of intersecting curves is. Even then, multiple volumes could coexist as leaves on the same tree level pointing to the same curve.

**Comment by Chlumsky** [comment]
The problem definition as it is stated in the first post is no longer correct. There have been some fundamental changes to the algorithm since then, which caused that it is no longer sufficient to select edges based on their true distance, and the pseudo-distance metric sometimes comes into play.

I have given this some thought later on and found out that the real problem with the pseudo-distance metric is that it takes into account the infinite continuations of all edge segments. This means that any sort of bounding hierarchy is not applicable because the individual components are literally *unbounded* - they continue to infinity in two directions.

However, it would be possible to apply the relatively straightforward bounding volume hierarchy optimization to the regular SDF mode and the old version of the algorithm, which only produces imprecise results in specific scenarios (mainly #25).

**Comment by Chlumsky** [comment]
The performance of the algorithm has been very significantly improved by 8ebb37da4edf90fe5110d4481e95a534ad0c2590 and subsequent tweaks, where partial results from previously computed pixels are stored and checked in order to skip edge segments that are definitely too far away to be relevant. I am currently satisfied with the algorithm's performance, so I am closing this issue. I am also working on a Vulkan-based GPU implementation which will be available in the future for those who still find the CPU implementation too slow.
