### ISSUE TITLE
Complex line could be rewritten to be clearer and faster

### ISSUE THREAD

**Issue by erich666** [Chlumsky/msdfgen#62]
A minor thing, but [this line of code](https://github.com/Chlumsky/msdfgen/blob/master/core/edge-coloring.cpp#L56) in edge-coloring.cpp:

```contour->edges[(corner+i)%m]->color = (colors+1)[int(3+2.875*i/(m-1)-1.4375+.5)-3];```

is complex and hard to understand. I believe, if I've done the simplification correctly, this turns into:

```contour->edges[(corner+i)%m]->color = colors[int(2.875*i/(m-1) + 0.0625];```

The intent appears to split the colors into three groups, index 0, 1, and 2, about evenly divided among those groups. Adding a comment here as to intent would also be nice.

**Comment by Chlumsky** [comment]
You're right that this line is terrible and you guessed the intent correctly, but I'm pretty sure the part with adding and subtracting 3 was important because of rounding negative numbers.

**Comment by erich666** [comment]
Ah, thanks. For i = 0, for example, your code will come out as -0.9375, with int() (vs. floor) pushing that to 0. I was thinking that trick was getting used here, but wasn't quite seeing it. So the intent really is to return color[1] or color[2] - got it. And these get returned with the range i=0..m*2/3 giving an index of 1, higher giving two. So m=6 means 1,1,1,1,2,2 for the indices returned. Good enough. Me, I think I would have gone with:

```contour->edges[(corner+i)%m]->color = (i < m*2/3) ? colors[1] : colors[2];```

or whatever your comparison is meant to be, as the intent is much clearer. I think your intent is to avoid any "if/then/else" test, which can slow code down. However, I believe simple "? ... :" trinary operations like this can get turned in a succession of steps by the compiler itself. Basically, I would recommend against out-guessing the compiler on this sort of thing, unless you know that overall, on a range of CPUs, doing so is a significant win in an inner loop (which might be the case, in which case a comment would be nice). "Premature optimization is the root of all evil" and all that - I like coding for readability unless I've proven with timings that some alternate, weird form is considerably faster.

**Comment by Chlumsky** [comment]
No, it definitely is supposed to output all three indices (0, 1, 2). Actually, I think your original post is correct (except for the missing parenthesis), negative numbers are no longer an issue when since you removed the +1. I don't really remember why I wrote it that way and didn't bother to simplify it, but I was probably really tired.

**Comment by erich666** [comment]
Sorry, I removed my reply (it was wrong!) and started on a corrected version. Then I just saw your reply.

I've gone round and round on this one. Let's look at what you're taking the "int" of:

```int(3+2.875*i/(m-1)-1.4375+.5)```

That can certainly be simplified with no loss to:

```int(2.875*i/(m-1)+ 3.5 -1.4375)```

to

```int(2.875*i/(m-1)+ 2.0625)```


Note how this value is always going to be a positive value, e.g. if i==0, then the value is 2.0625. This goes to an integer of 2. Three is subtracted, then at the start you add 1 to the color array, so this ends up with an index value of 0. Which is what I'd expect. Note that the weird behavior of "int," that int(-0.99) and int(0.99) both go to 0, doesn't come into play.

Anyway, that's as far as I got when you confirmed your intent. Yes, I entirely get why that code got the way it is, one of those "debug, debug, and debug again, aha, finally got the right formula!" kinds of things. Me, I'm just happy I truly understand it now. Super-minor point, but understanding the intent was the main thing for me. You might not want to touch the code, but a comment would be nice.

**Comment by Chlumsky** [comment]
Alright, since you decided to dissect this particular formula so much, I have also looked at it and believe that now I know exactly how it came to be. This was probably my exact thought process:

OK, I need the values to be symmetrical around one, so it will be best to have the formula return -1, 0, +1 instead of 0, 1, 2, so I just need to change the array to `(colors+1)` for that. At this point, I probably came up with some kind of genius graph and equation on paper and got the formula

`round(2.875*i/(m-1)-1.4375)`,

which is quite reasonable. Now, I probably didn't want to bring math functions into this, and wasn't sure if C even has `round` (still am not), so instead I added 0.5 so that I can simply convert to int, which is like `floor`. Then I realized that it won't work for negative numbers, so I added 3 for good measure, only to subtract it after the conversion, and that resulted in the expression you are looking at.

I also remember that I specifically tested this expression for ranges of `m`, so after I confirmed that it works as intended, I thought I better not touch it. "Don't fix what ain't broken" is a motto I live by.

**Comment by erich666** [comment]
> I thought I better not touch it

Exactly. Like I said, "You might not want to touch the code, but a comment would be nice." And your logic is just about what I thought it was, "we want -1, 0, 1, let's shift the color pointer by 1," etc. and keep working on the formula until it was right.

I'm writing about MSDF a bit in an article about fast and accurate text rendering, referencing your work and other techniques. So I thought I'd "give back" a little, since you so kindly made this code available for distribution. I was simply suggesting an improvement, as it helps anyone (like me) trying to read the code - I had hoped for "oh, adding a comment would be good." I could make a pull request myself, but that seemed overkill for a one-line comment.

BTW, if you ever want to write a paper on improvements you've made, please consider http://jcgt.org, which likes practical work such as this example: http://jcgt.org/published/0006/02/02/ that recently came out there.
