### ISSUE TITLE
Shouldn't SDF be two times wider?

### ISSUE THREAD

**Issue by gregee123** [Chlumsky/msdfgen#72]
I run msdfgen with these parameters:

msdfgen.exe sdf -defineshape "{ 1471,0; 1149,0; 1021,333; 435,333; 314,0; 0,0; 571,1466; 884,1466; # }{ 926,580; 724,1124; 526,580; # }" -size 256 256 -range 300 -autoframe

bounds = 0, 0, 1471, 1466
scale = 0.123611781748
translate = 300, 302.5

msdfgen.exe sdf -defineshape "{ 1471,0; 1149,0; 1021,333; 435,333; 314,0; 0,0; 571,1466; 884,1466; # }{ 926,580; 724,1124; 526,580; # }" -size 256 256 -pxrange 32 -autoframe

bounds = 0, 0, 1471, 1466
scale = 0.130523453433
translate = 245.166666667, 247.666666667
range = 245.166666667

In both cases even though the values of scale, translation, and range are calucalted perfectly correctly the generated sdf is way too narrow (in fact it should be exactly twice as wide!), hence the generated texture has a lot of black space around it. A temporary fix is to call the genereting method like this: generateSDF(sdf, shape, 2 * range, scale, translate); but surely it shouldn't be that way, correct?

----

I also posted this to ckohnert.

**Comment by Chlumsky** [comment]
No. Although there is more than one interpretation of what range could mean and you're describing one of them, in MSDFGEN, the meaning is the distance between the lowest and highest representable signed distance, that is, between a fully black and fully white SDF pixel. In your second example, you can easily check that this property holds, as the horizontal black-white gradient is 32 pixels high.

You are right about the unnecessary black space in the output though. It's likely that there's a bug in the autoframe logic, which also expected the range to be two times larger, although this isn't too serious, because the autoframe switch is intended for testing only and doesn't claim to use the minimum possible space.

**Comment by gregee123** [comment]
So it's the scaling and translation that's miscalculated after all. You should halve the range / pxrange arg value for the purpose of autoframing but pass the full value to the generator. Seems like you got confused yourself when writing that bit of code.

Thanks for clarification.
