### ISSUE TITLE
Glitches in MSDF

### ISSUE THREAD

**Issue by gregee123** [Chlumsky/msdfgen#74]
Using a very popular font Arial Black:

 msdf -font ariblk.ttf 120 -size 1024 1024 -pxrange 256 -autoframe -testrender render.png 512 512

I also changed the rendering method to visualize the median value of msdf:

void renderSDF(Bitmap<float> &output, const Bitmap<FloatRGB> &sdf, double pxRange) {
    int w = output.width(), h = output.height();
    pxRange *= (double) (w+h)/(sdf.width()+sdf.height());
    for (int y = 0; y < h; ++y)
        for (int x = 0; x < w; ++x) {
            FloatRGB s = sample(sdf, Point2((x+.5)/w, (y+.5)/h));
			output(x, y) = median(s.r, s.g, s.b); // distVal(median(s.r, s.g, s.b), pxRange); // here!!!
        }
}

Result in the attached png. I observed nothing similar when using plain sdf instead..

![msdf_glitch](https://user-images.githubusercontent.com/7345083/55480906-8cf09f80-5621-11e9-8fb9-0570fadfc55d.png)

**Comment by Chlumsky** [comment]
Yes, this is a known interpolation artifact. These are the reason that the [msdfErrorCorrection](/Chlumsky/msdfgen/blob/master/core/msdfgen.cpp#L47) function exists. But I don't see why it's an issue in this case, since the artifacts are nowhere near the edge and won't have an impact on rendering.

**Comment by gregee123** [comment]
I will have an impact on rendering unless all one does with the sdf is filling the outline with some color. In which case a few pixel wide sdf at high enough resolution would do.

From what I understand msdfErrorCorrection is already called from inside generateMSDF but fails to correct the issue. 

Admittedly, I can't claim I understand how pixelClash function works and indeed whether or not it actually detects those particular pixels. If so clearly replacing color components values with their median in a clashing pixel doesn't always work. Do you think interpolating the medians of the neighbouring   **non**-clashing pixels and ignoring the value of the clashing pixel itself altogether could work?

Info appreciated.

**Comment by Chlumsky** [comment]
No, the median values are always correct at the distance field points, they can only be wrong in-between due to interpolation. If this happens, the fault hasn't been detected by `pixelClash`.

I'll try to explain this in detail, since you seem interested. Basically, at each point, two of the three channels are the same and represent the real distance. Unless this is close to some key point, the third channel has a sort of "don't care" value, which continues in a smooth gradient from that part of the SDF, where this channel was the median. However, at some point, this third channel has to switch sharply, typically between a large positive value and a large negative value (but not in this case, more on that later), because in the next part, it's going to have to be a part of another gradient. These are the very visible discontinuities. In theory, this shouldn't be a problem - for example, if at one point, the three distances are (130, 6, 6) and at the next (-90, 7, 7), the median still goes smoothly from 6 to 7.

What is a problem, is when two different discontinuities touch. This means that the discontinuity is present at the point where the median channel switches. So, as another example, one pixel is (4, 4, -90) and the next is (4, -50, 4). At both points, the median is the same - 4. However, halfway between them, the value is interpolated as (4, -23, -43), making the median -23. This would result in a rendering artifact, since 4 is positive (inside shape) but -23 is negative (outside).

Therefore the error correction function attempts to detect such cases and resolve them by changing one of the two pixels to (4, 4, 4). However, the function is written in such a way that it only detects errors that would cause the median distance to have the wrong sign (that's the `< .5f` part). In your case, the value simply skips between different distances with the correct sign, so the detection would have to be changed to account for these cases as well.

**Comment by gregee123** [comment]
Appreciate the explanation.

Just to make sure. Now I understand that the case can be narrowed down two points equidistant from two (possibly more?) edges. Is there a point in GenerateMSDF() where this special case is somehow handled or is it that the value of components is determined by whichever edge happens to be iterated over first?

Could you save me some time and point me to a place in GenerateMSDF() to detect and solve for a value of multiple distances meeting at one point.

I can't tell for certain but I suspect the error correction function simply doesn't have enough data to work properly perhaps some helper metadata could help. I'm getting ahead of myself but this surely shouldn't be impossible to fix in one way or another.

**Comment by Chlumsky** [comment]
As I said, all you need to change is the `pixelClash` function. It has all the necessary data.

Or, maybe you can come up with a way to prevent this type of error earlier in the algorithm, instead of rectifying it after the fact, but I haven't been able to do that.

**Comment by Chlumsky** [comment]
Alright, I have updated the error correction function (as well as many other things) and it should now handle these cases better.

**Comment by gregee123** [comment]
Having tested all the fonts I had problems with before I can confirm there are no artifacts in msdf.

Thanks a ton!
