### ISSUE TITLE
Supported compilers / C++03 support?

### ISSUE THREAD

**Issue by dutow** [Chlumsky/msdfgen#88]
The code currently uses a definition named `MSDFGEN_USE_CPP11`, and mostly ignores newer C++ features. However, even without this flag, it uses a C++11 feature (explicit cast operators were added in C++11), which means building it with a C++98/03 compiler isn't possible.

Either this issue should be fixed (if you want to have C++03 support), or the macro and its use removed (and then the codebase could be modernized/simplified at other places too).

Or as a more generic question: do you have a list of supported compilers/standards?

(I don't need C++03 support, I'm only planning on submitting a CMake improvement pull request, and noticed this issue during testing it. I can also submit a PR about this issue, based on the answer for the above question)

**Comment by Chlumsky** [comment]
The issue with overloaded explicit cast operators has been fixed. The `MSDFGEN_USE_CPP11` flag is mostly legacy, and it exists because I wanted to maximize compiler compatibility at the time I started working on this (2014). I imagine that C++11 support is not really a problem at this point, so it could be just ignored and assumed to be always defined or even removed in the future.
