### ISSUE TITLE
Issues with various fonts when generating small MSDFs (< 24x24)

### ISSUE THREAD

**Issue by romainguy** [Chlumsky/msdfgen#9]
I'm running into pretty severe quality issues when trying to generate MSDFs for various glyphs in popular fonts (such as Google's [Roboto](https://www.google.com/fonts/specimen/Roboto)). Here is for instance the glyph 'A' rendered at 64x64 from a 16x16 MSDF (generated using `-size 16 16 -pxrange 1 -autoframe`):

![Roboto](https://cloud.githubusercontent.com/assets/869684/14895116/dc77aa5e-0d2b-11e6-979c-92bfbab63d8c.png)

Using a larger pxrange makes the problem even worse. Generating larger MSDFs wouldn't be much of an issue if minification worked well.

**Comment by Chlumsky** [comment]
1. Do not use pxrange below 2.
2. As I said in #1, 16x16 just isn't sufficient in 99% cases, so use a larger size.

With pxrange 1 you're not really generating a distance field anymore, it almost becomes just an image of the glyph, and it will always look wavy. I don't see how increasing it would make the problem worse, except that the glyph then gets slightly less space in the SDF. If you increase size by 2 for every pxrange, the size of the glyph should stay the same, and the result can only improve.

I'm not sure what you mean by "if minification worked well". Do you mean the test renders from my program or distance field rendering in general? I admit I didn't think of the possibility of making test renders smaller than the distance field at all, and that's why they may not look good, but you can definitely make minification work well in your shader, for example by using multisampling.

**Comment by romainguy** [comment]
OK this makes more sense to me now. When using a pxrange greater than 1
with a 16x16 MSDF the result barely looks like a glyph anymore.

For minification I assumed you were doing the same thing a shader would do.

Thanks for the quick reply!

**Comment by Chlumsky** [comment]
I have tried generating a test render smaller than the distance field by the program for the first time right now, and the result surprised me. I have no idea why it makes the anti-aliasing completely drop out and will look into it.

**Comment by Chlumsky** [comment]
Thanks for bringing this to my attention, it was a major oversight on my part. The issue with minification is now fixed, and what I have tried looks pretty good. However, it requires a higher range value than default, e.g. at least -pxrange 8 for reduction to 25%.

**Comment by romainguy** [comment]
Thanks for the info and more importantly thanks for the fix!
